### ISSUE TITLE
<cstr> guard 

### ISSUE THREAD

**Issue by intrig** [intrig/xenon#3]
The cstr element blindly reads until it finds a '\0'.  It should be limited by the remaining bits in the record and by the max attribute.  

Also, it does not work for non-byte aligned cstr.  This should either be fixed or fail gracefully.

**Comment by DaveCausey** [comment]
Also, it appears to add the null terminator to the string itself, resulting in null characters in the decoder output. The terminating null should not be included in the length of the string.

**Comment by intrig** [comment]
Yes, I remember you saying this and I looked into it but I couldn't 
easily see the problem.  I will fix it though.

**Comment by intrig** [comment]
Ok, fixed the null char thing maybe.  Since there are not tests for this feature I feel no reason to verify my fixes work.  But I'm pretty confident.

**Comment by intrig** [comment]
Ok, fixed the null char problem.  Since this is an untested feature I feel no need to verify my fixes, but I'm pretty confident.
