### ISSUE TITLE
Compilation Time

### ISSUE THREAD

**Issue by wythe** [intrig/xenon#9]
Programs including `xddl.h` take quite a long time to compile.  The main reason is that all the `xspx` generated code is all in a header file.  `xspx` should be given an option to generate a source file named `xddl.cpp` that can be compiled into `xenon.a`.  This would also help hide some of the internal API.

**Comment by intrig** [comment]
Although improvements can still be made, this issue has been largely resolved in Version 2.1.2. See the #10 patch notes.
